### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by hacdias** [tableflip/ipfs-fuse#1]
Hey @alanshaw,

I'm trying to use this on Windows and I've installed Donaky. Although, this doesn't seem to be working at all. I run `ipfs-fuse` and nothing happens. I activated the debug thingy via the Env variable and nothing was printed.

![image](https://user-images.githubusercontent.com/5447088/37683136-7f545a56-2c83-11e8-8535-045e47ed5aa6.png)

**Comment by alanshaw** [comment]
Oh cool, ok I never tested it on Windows. I'll take a look when I get a moment. Thanks @hacdias
