### ISSUE TITLE
Is Python really required?

### ISSUE THREAD

**Issue by happybeing** [tableflip/ipfs-fuse#2]
I have Python, so this question is not about problems installing but because I'm looking at what's involved in creating a new fuse mount.

I've looked at ipfs.io to see if its related to ipfs, and at this repo here and can't see where Python might be involved in the install, so can you point this out for me? What is it that brings it into the project?

**Comment by alanshaw** [comment]
[fuse-bindings](https://github.com/mafintosh/fuse-bindings) has a native addon that uses [node-gyp](https://github.com/nodejs/node-gyp) to install it - node-gyp requires python.

HTH
