### ISSUE TITLE
npm install fail 

### ISSUE THREAD

**Issue by royforu** [tableflip/ipfs-fuse#4]
Hi @alanshaw ,
when i execute npm install -g ipfs-fuse, i got the following error message, and also found 
ipfs-api  has renamed to ipfs-http-client.     
   
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Package fuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `fuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fuse' found
gyp: Call to 'pkg-config fuse --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/roy/.nvm/v11.3.0/lib/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-42-generic
gyp ERR! command "/home/roy/.nvm/v11.3.0/bin/node" "/home/roy/.nvm/v11.3.0/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/roy/.nvm/v11.3.0/lib/node_modules/ipfs-fuse/node_modules/fuse-bindings
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fuse-bindings@2.11.2 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fuse-bindings@2.11.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/roy/.npm/_logs/2018-12-14T03_59_49_739Z-debug.log

Can you help? 
Thank you very much. 

my env: 
os: ubuntu: 18.4.0
node version: v11.3.0
npm version: v6.4.0
node-gyp version: v3.8.0
python version: 2.7.15rc1

**Comment by alanshaw** [comment]
You need to install FUSE first - https://github.com/tableflip/ipfs-fuse/blob/master/INSTALL.md#install
